[2025-08-02T19:54:59.819+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: gcs_load_mutiple_csv_v1.load_cards_to_gcs manual__2025-08-02T19:54:54.761103+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
