[2025-08-02T19:29:00.454+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-02T19:29:00.484+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_load_mutiple_csv_v1.load_cards_to_gcs manual__2025-08-02T19:28:53.520249+00:00 [queued]>
[2025-08-02T19:29:00.501+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_load_mutiple_csv_v1.load_cards_to_gcs manual__2025-08-02T19:28:53.520249+00:00 [queued]>
[2025-08-02T19:29:00.502+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-02T19:29:00.528+0000] {taskinstance.py:2330} INFO - Executing <Task(LocalFilesystemToGCSOperator): load_cards_to_gcs> on 2025-08-02 19:28:53.520249+00:00
[2025-08-02T19:29:00.549+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=540) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-02T19:29:00.554+0000] {standard_task_runner.py:63} INFO - Started process 548 to run task
[2025-08-02T19:29:00.553+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'gcs_load_mutiple_csv_v1', 'load_cards_to_gcs', 'manual__2025-08-02T19:28:53.520249+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/gcs_load_dag.py', '--cfg-path', '/tmp/tmpt_srzoz2']
[2025-08-02T19:29:00.560+0000] {standard_task_runner.py:91} INFO - Job 21: Subtask load_cards_to_gcs
[2025-08-02T19:29:00.686+0000] {task_command.py:426} INFO - Running <TaskInstance: gcs_load_mutiple_csv_v1.load_cards_to_gcs manual__2025-08-02T19:28:53.520249+00:00 [running]> on host 06d424bf0ee1
[2025-08-02T19:29:00.844+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gcs_load_mutiple_csv_v1' AIRFLOW_CTX_TASK_ID='load_cards_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2025-08-02T19:28:53.520249+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-02T19:28:53.520249+00:00'
[2025-08-02T19:29:00.847+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-02T19:29:00.864+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-08-02T19:29:00.868+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-08-02T19:29:00.871+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-02T19:29:00.888+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 111, in execute
    hook.upload(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 528, in upload
    client = self.get_conn()
             ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 173, in get_conn
    credentials=self.get_credentials(), client_info=CLIENT_INFO, project=self.project_id
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 332, in get_credentials
    credentials, _ = self.get_credentials_and_project_id()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 308, in get_credentials_and_project_id
    credentials, project_id = get_credentials_and_project_id(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 371, in get_credentials_and_project_id
    return _CredentialProvider(*args, **kwargs).get_credentials_and_project()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 245, in get_credentials_and_project
    credentials, project_id = self._get_credentials_using_key_path()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 292, in _get_credentials_using_key_path
    raise AirflowException("Unrecognised extension for key file.")
airflow.exceptions.AirflowException: Unrecognised extension for key file.
[2025-08-02T19:29:00.902+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=gcs_load_mutiple_csv_v1, task_id=load_cards_to_gcs, run_id=manual__2025-08-02T19:28:53.520249+00:00, execution_date=20250802T192853, start_date=20250802T192900, end_date=20250802T192900
[2025-08-02T19:29:00.924+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 21 for task load_cards_to_gcs (Unrecognised extension for key file.; 548)
[2025-08-02T19:29:00.972+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-02T19:29:01.001+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-02T19:29:01.004+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
