[2025-08-10T15:46:20.572+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-10T15:46:20.611+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_pipeline_v1.dbt_run manual__2025-08-10T15:46:17.359464+00:00 [queued]>
[2025-08-10T15:46:20.624+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_pipeline_v1.dbt_run manual__2025-08-10T15:46:17.359464+00:00 [queued]>
[2025-08-10T15:46:20.634+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-10T15:46:20.656+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2025-08-10 15:46:17.359464+00:00
[2025-08-10T15:46:20.668+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=185) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-10T15:46:20.670+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_pipeline_v1', 'dbt_run', 'manual__2025-08-10T15:46:17.359464+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/dbt_run_pipeline_v1.py', '--cfg-path', '/tmp/tmpmr7x59tr']
[2025-08-10T15:46:20.671+0000] {standard_task_runner.py:63} INFO - Started process 186 to run task
[2025-08-10T15:46:20.672+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask dbt_run
[2025-08-10T15:46:20.791+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_run_pipeline_v1.dbt_run manual__2025-08-10T15:46:17.359464+00:00 [running]> on host 53d32f12f97d
[2025-08-10T15:46:20.965+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_run_pipeline_v1' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-08-10T15:46:17.359464+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-10T15:46:17.359464+00:00'
[2025-08-10T15:46:20.967+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-10T15:46:21.015+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-10T15:46:21.016+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run']
[2025-08-10T15:46:21.040+0000] {subprocess.py:86} INFO - Output:
[2025-08-10T15:46:25.224+0000] {subprocess.py:93} INFO - [0m15:46:25  Running with dbt=1.10.7
[2025-08-10T15:46:32.800+0000] {subprocess.py:93} INFO - [0m15:46:32  Registered adapter: bigquery=1.10.1
[2025-08-10T15:46:33.397+0000] {subprocess.py:93} INFO - [0m15:46:33  Unable to do partial parsing because of a version mismatch
[2025-08-10T15:46:36.187+0000] {subprocess.py:93} INFO - [0m15:46:36  Found 8 models, 4 sources, 496 macros
[2025-08-10T15:46:36.192+0000] {subprocess.py:93} INFO - [0m15:46:36
[2025-08-10T15:46:36.193+0000] {subprocess.py:93} INFO - [0m15:46:36  Concurrency: 1 threads (target='dev')
[2025-08-10T15:46:36.195+0000] {subprocess.py:93} INFO - [0m15:46:36
[2025-08-10T15:46:36.216+0000] {subprocess.py:93} INFO - [0m15:46:36
[2025-08-10T15:46:36.217+0000] {subprocess.py:93} INFO - [0m15:46:36  Finished running  in 0 hours 0 minutes and 0.02 seconds (0.02s).
[2025-08-10T15:46:36.219+0000] {subprocess.py:93} INFO - [0m15:46:36  Encountered an error:
[2025-08-10T15:46:36.220+0000] {subprocess.py:93} INFO - Database Error
[2025-08-10T15:46:36.220+0000] {subprocess.py:93} INFO -   [Errno 2] No such file or directory: 'C:\\Users\\RSK_T14s\\Documents\\Full Stack Data Project\\Dataverse-360\\***\\gcp\\dataverse-360-02dd77a51fd4.json'
[2025-08-10T15:46:38.847+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-08-10T15:46:38.852+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-10T15:46:38.870+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-08-10T15:46:38.878+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_run_pipeline_v1, task_id=dbt_run, run_id=manual__2025-08-10T15:46:17.359464+00:00, execution_date=20250810T154617, start_date=20250810T154620, end_date=20250810T154638
[2025-08-10T15:46:38.904+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 186)
[2025-08-10T15:46:38.952+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-10T15:46:38.980+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-10T15:46:38.983+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
