[2025-08-02T20:20:47.061+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-02T20:20:47.086+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_move_landing_to_raw_v1.move_cards_file manual__2025-08-02T20:20:42.000837+00:00 [queued]>
[2025-08-02T20:20:47.097+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_move_landing_to_raw_v1.move_cards_file manual__2025-08-02T20:20:42.000837+00:00 [queued]>
[2025-08-02T20:20:47.098+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-02T20:20:47.118+0000] {taskinstance.py:2330} INFO - Executing <Task(GCSToGCSOperator): move_cards_file> on 2025-08-02 20:20:42.000837+00:00
[2025-08-02T20:20:47.135+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=474) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-02T20:20:47.140+0000] {standard_task_runner.py:63} INFO - Started process 481 to run task
[2025-08-02T20:20:47.141+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'gcs_move_landing_to_raw_v1', 'move_cards_file', 'manual__2025-08-02T20:20:42.000837+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/gcs_load_dag.py', '--cfg-path', '/tmp/tmp6kk4ob9b']
[2025-08-02T20:20:47.146+0000] {standard_task_runner.py:91} INFO - Job 34: Subtask move_cards_file
[2025-08-02T20:20:47.245+0000] {task_command.py:426} INFO - Running <TaskInstance: gcs_move_landing_to_raw_v1.move_cards_file manual__2025-08-02T20:20:42.000837+00:00 [running]> on host 06d424bf0ee1
[2025-08-02T20:20:47.399+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gcs_move_landing_to_raw_v1' AIRFLOW_CTX_TASK_ID='move_cards_file' AIRFLOW_CTX_EXECUTION_DATE='2025-08-02T20:20:42.000837+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-02T20:20:42.000837+00:00'
[2025-08-02T20:20:47.403+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-02T20:20:47.417+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-08-02T20:20:47.427+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-08-02T20:20:47.429+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-02T20:20:47.443+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/gcs_to_gcs.py", line 281, in execute
    self._copy_source_without_wildcard(hook=hook, prefix=prefix)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/gcs_to_gcs.py", line 388, in _copy_source_without_wildcard
    objects = hook.list(
              ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 768, in list
    self._list(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 804, in _list
    client = self.get_conn()
             ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 173, in get_conn
    credentials=self.get_credentials(), client_info=CLIENT_INFO, project=self.project_id
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 332, in get_credentials
    credentials, _ = self.get_credentials_and_project_id()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 308, in get_credentials_and_project_id
    credentials, project_id = get_credentials_and_project_id(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 371, in get_credentials_and_project_id
    return _CredentialProvider(*args, **kwargs).get_credentials_and_project()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 217, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: The `keyfile_dict`, `key_path`, `credential_config_file`, `is_anonymous` and `key_secret_name` fields are all mutually exclusive. Please provide only one value.
[2025-08-02T20:20:47.450+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=gcs_move_landing_to_raw_v1, task_id=move_cards_file, run_id=manual__2025-08-02T20:20:42.000837+00:00, execution_date=20250802T202042, start_date=20250802T202047, end_date=20250802T202047
[2025-08-02T20:20:47.489+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 34 for task move_cards_file (The `keyfile_dict`, `key_path`, `credential_config_file`, `is_anonymous` and `key_secret_name` fields are all mutually exclusive. Please provide only one value.; 481)
[2025-08-02T20:20:47.517+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-02T20:20:47.534+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
