[2025-08-02T20:07:15.665+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-02T20:07:15.694+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_upload_from_local_v1.upload_users_csv_to_gcs_landing manual__2025-08-02T20:07:10.898610+00:00 [queued]>
[2025-08-02T20:07:15.704+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_upload_from_local_v1.upload_users_csv_to_gcs_landing manual__2025-08-02T20:07:10.898610+00:00 [queued]>
[2025-08-02T20:07:15.706+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-02T20:07:15.728+0000] {taskinstance.py:2330} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_users_csv_to_gcs_landing> on 2025-08-02 20:07:10.898610+00:00
[2025-08-02T20:07:15.746+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=291) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-02T20:07:15.749+0000] {standard_task_runner.py:63} INFO - Started process 297 to run task
[2025-08-02T20:07:15.749+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'gcs_upload_from_local_v1', 'upload_users_csv_to_gcs_landing', 'manual__2025-08-02T20:07:10.898610+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/gcs_load_dag.py', '--cfg-path', '/tmp/tmp5_ko6oxg']
[2025-08-02T20:07:15.758+0000] {standard_task_runner.py:91} INFO - Job 28: Subtask upload_users_csv_to_gcs_landing
[2025-08-02T20:07:15.856+0000] {task_command.py:426} INFO - Running <TaskInstance: gcs_upload_from_local_v1.upload_users_csv_to_gcs_landing manual__2025-08-02T20:07:10.898610+00:00 [running]> on host 06d424bf0ee1
[2025-08-02T20:07:15.995+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gcs_upload_from_local_v1' AIRFLOW_CTX_TASK_ID='upload_users_csv_to_gcs_landing' AIRFLOW_CTX_EXECUTION_DATE='2025-08-02T20:07:10.898610+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-02T20:07:10.898610+00:00'
[2025-08-02T20:07:15.998+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-02T20:07:16.015+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-08-02T20:07:16.019+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-08-02T20:07:16.022+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-02T20:07:16.037+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 111, in execute
    hook.upload(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 528, in upload
    client = self.get_conn()
             ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 173, in get_conn
    credentials=self.get_credentials(), client_info=CLIENT_INFO, project=self.project_id
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 332, in get_credentials
    credentials, _ = self.get_credentials_and_project_id()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 308, in get_credentials_and_project_id
    credentials, project_id = get_credentials_and_project_id(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 371, in get_credentials_and_project_id
    return _CredentialProvider(*args, **kwargs).get_credentials_and_project()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 245, in get_credentials_and_project
    credentials, project_id = self._get_credentials_using_key_path()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 292, in _get_credentials_using_key_path
    raise AirflowException("Unrecognised extension for key file.")
airflow.exceptions.AirflowException: Unrecognised extension for key file.
[2025-08-02T20:07:16.045+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=gcs_upload_from_local_v1, task_id=upload_users_csv_to_gcs_landing, run_id=manual__2025-08-02T20:07:10.898610+00:00, execution_date=20250802T200710, start_date=20250802T200715, end_date=20250802T200716
[2025-08-02T20:07:16.066+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 28 for task upload_users_csv_to_gcs_landing (Unrecognised extension for key file.; 297)
[2025-08-02T20:07:16.126+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-02T20:07:16.141+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
